sudo: required
services: 
  - nginx

before_install:
  - docker build -t mituso/react-app-client -f ./my-app/Dockerfile.dev ./client


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "nginx"
  env: "Nginx-env"
  bucket_name: "elasticbeanstalk-us-east-2-190683250872"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY