sudo: required
services: 
  - nginx

before_install:
  - docker build -t mituso/react-app-client -f ./my-app/Dockerfile.dev ./my-app

script:
  - docker run -e CI=true mituso/react-app-client npm test

after_success:
  - docker build -t mituso/react-app-client ./my-app
  - docker build -t mituso/multi-nginx-client ./nginx
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker push react-app-client
  - docker push mituso/multi-nginx-client

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-190683250872"
  bucket_path: "dockerenv"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY